FSM:
  _: # enabled fsms
    Passive:
      id: 1
    FixStand:
      id: 2
    Velocity:
      id: 3
      type: RLBase

    Mimic_Dance_102: # uncomment to enable
      id: 101
      type: Mimic

    Mimic_Pico_Houtaitui4:
      id: 102
      type: Mimic

    Mimic_Pico_Dun:
      id: 103
      type: Mimic

    Mimic_Pico_Taitui:
      id: 104
      type: Mimic

    Mimic_Pico_Houtaitui:
      id: 105
      type: Mimic

    Mimic_Pico_Taitui2:
      id: 106
      type: Mimic

    Mimic_Dun:
      id: 107
      type: Mimic

    Mimic_Neutral_Walk_Forward:
      id: 108
      type: Mimic

  Passive:
    transitions: 
      FixStand: LT + up.on_pressed
    mode: [
      1,1,1,1,1,1,
      1,1,1,1,1,1,
      1,1,1,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,
    ]
    kd: [
      3,3,3,3,3,3,
      3,3,3,3,3,3,
      3,3,3,
      3,3,3,3,3,3,3,  
      3,3,3,3,3,3,3,  
    ]
  FixStand:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    kp: [
      100., 100., 100., 150., 40., 40.,
      100., 100., 100., 150., 40., 40.,
      200,40,40,
      40,40,40,40,40,40,40,
      40,40,40,40,40,40,40,
    ]
    kd: [
      2,2,2,4,2,2,
      2,2,2,4,2,2,
      5,5,5,
      1,1,1,1,1,1,1,
      1,1,1,1,1,1,1,
    ]
    ts: [0, 3]
    qs: [
      [],
      [ -0.1, 0,0,0.3,-0.2,0,
        -0.1, 0,0,0.3,-0.2,0,
        0,0,0,
        0, 0.25,0,0.97,0.15, 0,0,
        0, -0.25,0,0.97,-0.15, 0,0
      ]
    ]
  Velocity:
    transitions: 
      Passive: LT + B.on_pressed
      Mimic_Dance_102: LT(2s) + up.on_pressed
      Mimic_Pico_Houtaitui4: LT(2s) + left.on_pressed
      Mimic_Pico_Dun: LT(2s) + down.on_pressed
      Mimic_Pico_Taitui: LT(2s) + X.on_pressed
      Mimic_Pico_Houtaitui: LT(2s) + A.on_pressed
      Mimic_Pico_Taitui2: LT(2s) + right.on_pressed
      Mimic_Dun: LT(2s) + LB.on_pressed
      Mimic_Neutral_Walk_Forward: LT(2s) + Y.on_pressed

    policy_dir: config/policy/velocity
    # policy_dir: ../../../logs/rsl_rl/unitree_g1_29dof_velocity
  Mimic_Dance_102:
    transitions: 
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 60
    motion_file: config/policy/mimic/dance_102/params/G1_Take_102.bvh_60hz.csv
    policy_dir: config/policy/mimic/dance_102/
  Mimic_Pico_Houtaitui4:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 50
    motion_file: config/policy/mimic/pico_houtaitui4/params/pico_houtaitui4.csv
    policy_dir: config/policy/mimic/pico_houtaitui4/
  Mimic_Pico_Dun:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 50
    motion_file: config/policy/mimic/pico_dun/params/pico_dun.csv
    policy_dir: config/policy/mimic/pico_dun/
  Mimic_Pico_Taitui:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 50
    motion_file: config/policy/mimic/pico_taitui/params/pico_taitui.csv
    policy_dir: config/policy/mimic/pico_taitui/
  Mimic_Pico_Houtaitui:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 50
    motion_file: config/policy/mimic/pico_houtaitui/params/pico_houtaitui.csv
    policy_dir: config/policy/mimic/pico_houtaitui/
  Mimic_Pico_Taitui2:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 50
    motion_file: config/policy/mimic/pico_taitui2/params/pico_taitui2.csv
    policy_dir: config/policy/mimic/pico_taitui2/
  Mimic_Dun:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 50
    motion_file: config/policy/mimic/dun/params/dun.csv
    policy_dir: config/policy/mimic/dun/
  Mimic_Neutral_Walk_Forward:
    transitions:
      Passive: LT + B.on_pressed
      Velocity: RB + X.on_pressed
    fps: 60
    motion_file: config/policy/mimic/neutral_walk_forward/params/neutral_walk_forward.csv
    policy_dir: config/policy/mimic/neutral_walk_forward/
